version: '3.8'

services:
  api-1:
    build:
      context: ./api-1
    ports:
      - "5000:5000"
    networks:
      - custom-network

  api-2:
    build:
      context: ./api-2
    ports:
      - "5001:5001"
    depends_on:
      - api-1
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
